# This action publishes a package after you push a version number tag
name: Publish to GitHub Packages, create GitHub Release
on:
  push:
    tags:
      # filter to tags that look like a version
      # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-including-branches-and-tags
      - 'v[0-9]*'
jobs:
  publish:
    runs-on: ubuntu-20.04
    permissions: 
      contents: write # for gh-release
      packages: write # for npm publish
    steps:
      - uses: actions/checkout@v3
        with:
          # git fetch all branches instead of just the ref, and no --depth=1
          # required for testing that master is ancestor of tag
          fetch-depth: 0
        # since trigger is not a branch event, it will check out master
      - uses: actions/setup-node@v3
        # Setup .npmrc file to publish to GitHub Packages
        with:
          cache: 'yarn'
          node-version: '16'
          # create .npmrc with @themaven-net:registry=https://npm.pkg.github.com/
          scope: '@themaven-net'
          registry-url: 'https://npm.pkg.github.com'
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - name: Check that master is ancestor of the tag ${{ github.event.ref }}
        run: |
          GITHUB_REF_SHA=$(git rev-parse "$GITHUB_REF")
          MASTER_SHA=$(git rev-parse origin/master)
          if ! git merge-base --is-ancestor "$MASTER_SHA" "$GITHUB_REF_SHA"; then
            echo >&2 "Error: The pushed tag $GITHUB_REF ($GITHUB_REF_SHA) is not contained in master ($MASTER_SHA); aborting npm publish"
          fi
      - name: Check that version in package.json matches the tag ${{ github.event.ref }}
        run: |
          VERSION=$(jq --raw-output <package.json .version)
          EXPECTED_TAG=refs/tags/v$VERSION
          if [[ "$GITHUB_REF" != "$EXPECTED_TAG" ]]; then
            echo >&2 "Error: the pushed tag $GITHUB_REF did not match package.json $VERSION; aborting npm publish"
            exit 2
          fi
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          generate_release_notes: true
