name: tests

# triggers
# https://docs.github.com/en/actions/reference/events-that-trigger-workflows
on:
  push:
  pull_request:
jobs:
  run-lint:
    # available runners:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: yarn install --frozen-lockfile
      - run: yarn test
